/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ImpersonationRouteImport } from './routes/impersonation'
import { Route as MessageRouteImport } from './routes/message'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ScammedRouteImport } from './routes/scammed'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as UrlRouteImport } from './routes/url'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as ApiAnalyzeImpersonationRouteImport } from './routes/api/analyze/impersonation'
import { Route as ApiAnalyzeMessageRouteImport } from './routes/api/analyze/message'
import { Route as ApiAnalyzeQrRouteImport } from './routes/api/analyze/qr'
import { Route as ApiAnalyzeUrlRouteImport } from './routes/api/analyze/url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonationRoute = ImpersonationRouteImport.update({
  id: '/impersonation',
  path: '/impersonation',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ScammedRoute = ScammedRouteImport.update({
  id: '/scammed',
  path: '/scammed',
  getParentRoute: () => rootRouteImport,
} as any)
const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlRoute = UrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeImpersonationRoute = ApiAnalyzeImpersonationRouteImport.update({
  id: '/api/analyze/impersonation',
  path: '/api/analyze/impersonation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeMessageRoute = ApiAnalyzeMessageRouteImport.update({
  id: '/api/analyze/message',
  path: '/api/analyze/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeQrRoute = ApiAnalyzeQrRouteImport.update({
  id: '/api/analyze/qr',
  path: '/api/analyze/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeUrlRoute = ApiAnalyzeUrlRouteImport.update({
  id: '/api/analyze/url',
  path: '/api/analyze/url',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impersonation': typeof ImpersonationRoute
  '/message': typeof MessageRoute
  '/overview': typeof OverviewRoute
  '/qr': typeof QrRoute
  '/scammed': typeof ScammedRoute
  '/tips': typeof TipsRoute
  '/url': typeof UrlRoute
  '/api/health': typeof ApiHealthRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/': typeof HistoryIndexRoute
  '/api/analyze/impersonation': typeof ApiAnalyzeImpersonationRoute
  '/api/analyze/message': typeof ApiAnalyzeMessageRoute
  '/api/analyze/qr': typeof ApiAnalyzeQrRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impersonation': typeof ImpersonationRoute
  '/message': typeof MessageRoute
  '/overview': typeof OverviewRoute
  '/qr': typeof QrRoute
  '/scammed': typeof ScammedRoute
  '/tips': typeof TipsRoute
  '/url': typeof UrlRoute
  '/api/health': typeof ApiHealthRoute
  '/history/$id': typeof HistoryIdRoute
  '/history': typeof HistoryIndexRoute
  '/api/analyze/impersonation': typeof ApiAnalyzeImpersonationRoute
  '/api/analyze/message': typeof ApiAnalyzeMessageRoute
  '/api/analyze/qr': typeof ApiAnalyzeQrRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impersonation': typeof ImpersonationRoute
  '/message': typeof MessageRoute
  '/overview': typeof OverviewRoute
  '/qr': typeof QrRoute
  '/scammed': typeof ScammedRoute
  '/tips': typeof TipsRoute
  '/url': typeof UrlRoute
  '/api/health': typeof ApiHealthRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/': typeof HistoryIndexRoute
  '/api/analyze/impersonation': typeof ApiAnalyzeImpersonationRoute
  '/api/analyze/message': typeof ApiAnalyzeMessageRoute
  '/api/analyze/qr': typeof ApiAnalyzeQrRoute
  '/api/analyze/url': typeof ApiAnalyzeUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/impersonation'
    | '/message'
    | '/overview'
    | '/qr'
    | '/scammed'
    | '/tips'
    | '/url'
    | '/api/health'
    | '/history/$id'
    | '/history/'
    | '/api/analyze/impersonation'
    | '/api/analyze/message'
    | '/api/analyze/qr'
    | '/api/analyze/url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/impersonation'
    | '/message'
    | '/overview'
    | '/qr'
    | '/scammed'
    | '/tips'
    | '/url'
    | '/api/health'
    | '/history/$id'
    | '/history'
    | '/api/analyze/impersonation'
    | '/api/analyze/message'
    | '/api/analyze/qr'
    | '/api/analyze/url'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/impersonation'
    | '/message'
    | '/overview'
    | '/qr'
    | '/scammed'
    | '/tips'
    | '/url'
    | '/api/health'
    | '/history/$id'
    | '/history/'
    | '/api/analyze/impersonation'
    | '/api/analyze/message'
    | '/api/analyze/qr'
    | '/api/analyze/url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ImpersonationRoute: typeof ImpersonationRoute
  MessageRoute: typeof MessageRoute
  OverviewRoute: typeof OverviewRoute
  QrRoute: typeof QrRoute
  ScammedRoute: typeof ScammedRoute
  TipsRoute: typeof TipsRoute
  UrlRoute: typeof UrlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  HistoryIdRoute: typeof HistoryIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  ApiAnalyzeImpersonationRoute: typeof ApiAnalyzeImpersonationRoute
  ApiAnalyzeMessageRoute: typeof ApiAnalyzeMessageRoute
  ApiAnalyzeQrRoute: typeof ApiAnalyzeQrRoute
  ApiAnalyzeUrlRoute: typeof ApiAnalyzeUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonation': {
      id: '/impersonation'
      path: '/impersonation'
      fullPath: '/impersonation'
      preLoaderRoute: typeof ImpersonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scammed': {
      id: '/scammed'
      path: '/scammed'
      fullPath: '/scammed'
      preLoaderRoute: typeof ScammedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url': {
      id: '/url'
      path: '/url'
      fullPath: '/url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/impersonation': {
      id: '/api/analyze/impersonation'
      path: '/api/analyze/impersonation'
      fullPath: '/api/analyze/impersonation'
      preLoaderRoute: typeof ApiAnalyzeImpersonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/message': {
      id: '/api/analyze/message'
      path: '/api/analyze/message'
      fullPath: '/api/analyze/message'
      preLoaderRoute: typeof ApiAnalyzeMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/qr': {
      id: '/api/analyze/qr'
      path: '/api/analyze/qr'
      fullPath: '/api/analyze/qr'
      preLoaderRoute: typeof ApiAnalyzeQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze/url': {
      id: '/api/analyze/url'
      path: '/api/analyze/url'
      fullPath: '/api/analyze/url'
      preLoaderRoute: typeof ApiAnalyzeUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ImpersonationRoute: ImpersonationRoute,
  MessageRoute: MessageRoute,
  OverviewRoute: OverviewRoute,
  QrRoute: QrRoute,
  ScammedRoute: ScammedRoute,
  TipsRoute: TipsRoute,
  UrlRoute: UrlRoute,
  ApiHealthRoute: ApiHealthRoute,
  HistoryIdRoute: HistoryIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  ApiAnalyzeImpersonationRoute: ApiAnalyzeImpersonationRoute,
  ApiAnalyzeMessageRoute: ApiAnalyzeMessageRoute,
  ApiAnalyzeQrRoute: ApiAnalyzeQrRoute,
  ApiAnalyzeUrlRoute: ApiAnalyzeUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
